examples/apt1.json
examples/idioms/course-of-action-to-block-network-traffic.json
examples/idioms/cve-in-an-exploit-target.json
examples/idioms/defining-campaigns-vs-threat-actors.json
examples/idioms/file-hash-reputation.json
examples/idioms/identifying-a-threat-actor-profile.json
examples/idioms/indicator-for-c2-ip-address.json
examples/idioms/indicator-for-malicious-URL.json
examples/idioms/indicator-to-campaign-relationship.json
examples/idioms/kill-chain.json
examples/idioms/linking-an-indicator-to-kill-chain-phase.json
examples/idioms/malicious-e-mail-indicator-with-attachment.json
examples/idioms/malware-characterization-using-maec.json
examples/idioms/malware-indicator-for-file-hash.json
examples/idioms/plain-wrapper-around-multiple-reports.json
examples/idioms/snort-test-mechanism.json
examples/idioms/threat-actor-leveraging-attack-patterns-and-malware.json
examples/idioms/victim-targeting-by-sector.json
examples/idioms/victim-targeting-for-a-campaign.json
examples/idioms/yara-test-mechanism.json

--Removed "version" property from all examples
--Other minor changes such as STIX patterning changes and removal of
pattern_lang properties

Updated APT1 and Idioms to RC4

---

schemas/common/cyber-observable-core.json
schemas/common/granular-marking.json
schemas/common/marking-definition.json
schemas/observables/artifact.json
schemas/observables/file.json
schemas/observables/network-traffic.json
schemas/observables/process.json
schemas/observables/software.json
schemas/observables/user-account.json
schemas/sdos/malware.json
schemas/sros/sighting.json

And fix some issues along the way.

Update schemas to WD01

---

schemas/observables/file.json
schemas/observables/process.json

Fix JSON Schema Lint errors

---

examples/campaign-and-threat-actors.json
examples/indicators-for-C2-with-COA.json
examples/threat-reports/poisonivy.json

Issue 34: Multiple Relationships with same ID--Fixed by creating new
ID's for the duplicates
Issue 35: Relationship points to Missing Object--It points to the
correct malware object now
Issue 36: Multiple Relationships with Same ID--fixed by generating new
ID's for those duplicated relationships
Also reformatted campaign-and-threat-actors.json with PrettyJSON

Fixed issues 34,35,36

---

schemas/common/cyber-observable-core.json
schemas/common/external-reference.json
schemas/common/hashes-type.json

- Update hashes key format requirements
- Remove description property from Cyber Observable objects
- Add hashes property to external reference objects

Update to 2.0 WD02

---

examples/threat-reports/apt1.json
examples/threat-reports/poisonivy.json

--Invalid timestamp "2006-06-00T00:00:00.000000Z" has now been fixed
--Updated others to be more precise
Fix #44, Close #45

Fixed invalid timestamp, updated others

---

schemas/common/marking-definition.json
schemas/common/timestamp.json
schemas/observables/file.json
schemas/observables/network-traffic.json
schemas/observables/process.json
schemas/observables/user-account.json
schemas/observables/x509-certificate.json

- Updated timestamp regex
- Cyber Observables which MUST have at least one of several optional properties
- Only use TLP instances from the Spec

Miscellaneous fixes

---

schemas/common/core.json

(make it easier to rewrite the error message)

Fix timestamp for validator

---

pattern_grammar/STIXPattern.g4

Also removed an obsolete comment.

Added support for 'NOT' qualifier before equality and order operators.

---

pattern_grammar/STIXPattern.g4

Fixed the integer literal tokens so that they will match all integers.
Fix #69

Fixed the integer literal tokens

---

pattern_grammar/STIXPattern.g4

Require correctly cased keywords in STIX patterns

---

examples/indicators-for-C2-with-COA.json
examples/threat-reports/apt1.json
schemas/common/identifier.json

Update UUIDv4 regex

---

schemas/common/hashes-type.json

Added TLSH to accepted hashing algorithms

---

schemas/common/url-regex.json
schemas/observables/email-addr.json

... instead of regexes. Fixes #100, fixes #111

Use uri and email formats built into JSON Schema

---

schemas/sdos/course-of-action.json

Revert Course of Action to 2.0 version

---

schemas/common/cyber-observable-core.json

Ensure SCO extensions follow naming requirements

---

schemas/sdos/identity.json
schemas/sdos/indicator.json
schemas/sdos/infrastructure.json
schemas/sdos/malware.json
schemas/sdos/report.json
schemas/sdos/threat-actor.json
schemas/sdos/tool.json

Make some properties optional

---

schemas/sdos/malware-analysis.json

Update malware-analysis to 2.1 WD07

---

schemas/common/core.json
schemas/common/cyber-observable-core.json
schemas/common/granular-marking.json
schemas/common/identifier.json

Ensure type/property names start with a letter

---

schemas/observables/software.json

Add swid property to Software

---

schemas/common/external-reference.json
schemas/common/hashes-type.json

And fix up the hashes-type schema.
Fix #106.

Update External Reference hashes key requirements

---

schemas/common/core.json

Make ms precision minimum for created/modified

---

schemas/sdos/malware.json

malware.os_execution_envs -> operating_system_refs

---

schemas/common/core.json
schemas/common/cyber-observable-core.json
schemas/common/properties.json

Fix property and extension name formats

---

.travis.yml
test_examples.sh

Related: https://github.com/ajv-validator/ajv-cli/issues/80

Add ajv plugin to fix tests using idn-hostname

---

.github/workflows/python-ci-tests.yml
.travis.yml

This Pull Request contains the following changes:
- Replace Travis CI with GitHub Actions as the test harness

GitHub Actions Migration

---

schemas/common/core.json
schemas/common/cyber-observable-core.json
schemas/common/extension-definition.json
schemas/common/extension.json
schemas/sdos/incident.json

* Add support for extensions
* Add incident stub

2.1 extensions

---

schemas/sdos/note.json

as dictated by the specification

Require 'content' on Notes

---

schemas/common/bundle.json

Add malware analysis into bundle schema

---

schemas/common/bundle.json

Merge the pull request from @oooooleg https://github.com/oasis-open/cti-stix2-json-schemas/pull/148 into the stix2.1 branch since it is applicable to stix2.1

Add malware-analysis to bundle

---

schemas/sdos/observed-data.json

simplify object_refs allowed patterns regex - resolves issue #182 in validator.

Merge schema master into Stix2.1 branch 
