oasis-open/cti-stix2-json-schemas

schemas/common/marking-definition.json

Restricting definition_type to one of ['statement', 'tlp'] is a SHOULD requirement, not a MUST requirement and thus should not be included in the schemas.
Close #1.

Remove marking-definition definition_type enum

---

schemas/common/url.json

Specifically, the one from https://gist.github.com/dperini/729294
Fix oasis-open/cti-stix2-json-schemas/issues/5

Use a different URL regex

---

examples/apt1.json
examples/idioms/course-of-action-to-block-network-traffic.json
examples/idioms/file-hash-reputation.json
examples/idioms/identifying-a-threat-actor-profile.json
examples/idioms/indicator-for-c2-ip-address.json
examples/idioms/indicator-for-malicious-URL.json
examples/idioms/indicator-to-campaign-relationship.json
examples/idioms/kill-chain.json
examples/idioms/linking-an-indicator-to-kill-chain-phase.json
examples/idioms/malicious-e-mail-indicator-with-attachment.json
examples/idioms/malware-characterization-using-maec.json
examples/idioms/malware-indicator-for-file-hash.json
examples/idioms/snort-test-mechanism.json
examples/idioms/threat-actor-leveraging-attack-patterns-and-malware.json
examples/idioms/victim-targeting-by-sector.json
examples/idioms/yara-test-mechanism.json
schemas/sdos/observed-data.json
tests/sdos/indicator/simple.json
tests/sdos/report/simple.json

-Adjusted idioms to work with RC3 specs
-Reformatted timestamps to be compliant with the timestamp format in the
specs
-Removed cybox instances
-Corrected kill chain phase and external-reference formats based on the
specs

Updated idioms/examples to RC3, fixed timestamps, removed cybox references

---

pattern_grammar/STIXPattern.g4

This corresponds to cti-pattern-matcher [PR#15](https://github.com/oasis-open/cti-pattern-matcher/pull/15).

Fix string literal escaping to match the spec

---

pattern_grammar/STIXPattern.g4

This corresponds to [PR#17](https://github.com/oasis-open/cti-pattern-matcher/pull/17) from the cti-pattern-matcher repo.

Removed NULL from the grammar.

---

pattern_grammar/STIXPattern.g4

This is the grammar update corresponding to cti-pattern-matcher [PR#20](https://github.com/oasis-open/cti-pattern-matcher/pull/20).
- All time units in WITHIN qualifiers are removed except seconds
- WITHIN seconds counts may now be either ints or floats

Fix WITHIN qualifier time units to agree with spec

---

README.md

Helps explain the clause "some requirements of the specification cannot be enforced in JSON schema alone."

List checks which the schemas cannot enforce

---

schemas/common/binary.json
schemas/common/cyber-observable-core.json
schemas/observables/artifact.json

`media: binaryEncoding` is only valid in JSON Hyper-Schema.
Found by oasis-open/cti-stix-validator#17

Fix binary-typed properties in Cyber Observable objects

---

pattern_grammar/STIXPattern.g4

Changed pattern grammar to disallow unquoted hyphens in property names.  Also changed the property name quote char to a single quote.

Update to disallow unquoted hyphens in property names.

---

pattern_grammar/STIXPattern.g4

Related Pull Request:
- https://github.com/oasis-open/cti-pattern-validator/pull/46
Related Issues: 
- https://github.com/oasis-open/cti-pattern-validator/issues/39
- https://github.com/oasis-open/cti-pattern-validator/issues/41
- https://github.com/oasis-open/cti-pattern-validator/issues/42
- https://github.com/oasis-open/cti-pattern-validator/issues/43

Add catch-all for unusable characters

---

pattern_grammar/STIXPattern.g4

Pattern validation was failing on the START STOP qualifier when the timestamp was in the format of
`START t'2016-06-01T00:00:00Z' STOP t'2016-06-01T01:11:11Z'`
The leading **t** in the timestamp was the culprit. Validation should work when the generated grammar files get incorporated into the pattern validator (https://github.com/oasis-open/cti-pattern-validator) .

change START STOP timestamp to TimestampLiteral

---

schemas/common/core.json
schemas/sdos/grouping.json
schemas/sdos/infrastructure.json
schemas/sdos/malware-analysis.json

Introducing schema for grouping, infrastructure, and malware-analysis objects based on STIX 2.1 WD04.
Ideally, the parent project will introduce a new branch for WD04. I'm happy to discard and resubmit the pull request if a better target becomes available. Please let me know if you would like me to do so.
Submitted under IBM's Entity CLA.

New SDOs introduced in STIX 2.1 WD04

---

examples/README.md
examples/infrastructure.json
schemas/common/cyber-observable-core.json
schemas/observables/artifact.json
schemas/observables/autonomous-system.json
schemas/observables/directory.json
schemas/observables/domain-name.json
schemas/observables/email-addr.json
schemas/observables/email-message.json
schemas/observables/file.json
schemas/observables/ipv4-addr.json
schemas/observables/ipv6-addr.json
schemas/observables/mac-addr.json
schemas/observables/mutex.json
schemas/observables/network-traffic.json
schemas/observables/process.json
schemas/observables/software.json
schemas/observables/url.json
schemas/observables/user-account.json
schemas/observables/windows-registry-key.json
schemas/observables/x509-certificate.json
schemas/sdos/infrastructure.json

In STIX 2.1 WD04, id is a required property for SCOs and the Infrastructure examples use the id field to express relationships. This pull request adds the id property to the SCOs. It also adds some of the infrastructure examples from STIX 2.1 WD04 to the examples directory to test the update. Finally, it adds the new aliases property to the Infrastructure object.
I have signed the CLA.

Schema updates for infrastructure examples

---

schemas/common/granular-marking.json

It would cause the validator to mark content as invalid...

add `id` as special-case option in regex for selector syntax

---

schemas/common/marking-definition.json

Make the schemas align with this statement from the spec: "Other instances of tlp-marking MUST NOT be used or created (the only instances of TLP marking definitions permitted are those defined here)."

Fix Marking Definition schema TLP checks

---

schemas/observables/windows-registry-key.json

This changes the whitelist regex on non-abbreviated hive names to a blacklist regex on abbreviated hive names.  I found some abbreviated hive names at https://en.wikipedia.org/wiki/Windows_Registry .  It includes HKLM, HKCC, HKCR, HKCU, HKU, so those are the values used in the schema.  I retained both lower and uppercase versions, since that's how the previous regex was written.
Fixes #143 .
Also fixes https://github.com/oasis-open/cti-stix-validator/issues/185 .
Also fixes https://github.com/oasis-open/cti-stix-generator/issues/19 .

Fix JSON schema for windows-registry-key SCO for hive names

---

pattern_grammar/STIXPattern.g4

The standard states that:
> A Comparison Operator MAY be preceded by the modifier NOT, in which case the resultant Comparison Expression is logically negated.
and the `EXISTS` set operator is defined under the comparison operators (together with `ISSUBSET` and `ISSUPERSET` under the set operators). I'm guessing the specification for the not syntax with set operators was missed when exists was added with stix 2.1 which introduced it.
This PR should make set operators consistent with the spec.
Closes #157

Fix exists grammar

---

schemas/observables/network-traffic.json

Thanks to @JasperJuergensen.
Closes #152.
Closes #153.

Fix network traffic http-request request_header

---

schemas/common/core.json

This isn't explicitly disallowed by the spec; see https://github.com/oasis-tcs/cti-stix2/issues/321.
`master` branch should be merged into `stix2.1` once this PR is merged in.
Fixes #160.

Allow -ext extensions in SDOs

---

schemas/sdos/observed-data.json

Addresses [Validator issue #182](https://github.com/oasis-open/cti-stix-validator/issues/182).  Adds a check for SDO object name patterns to the object_refs to deny.  Allows SCO and SRO refs.  
NOTE: Validator submodule links need correcting to match this update.
See also added Test in Validator to confirm allow/deny:
stix2validator/test/v21/observed_data_tests.py::ObservedDataTestCases::test_invalid_object_refs

Adds allow/deny to object_refs to prevent SDOs as refs in observed data
